### ISSUE TITLE
Where's the highlighting?

### ISSUE THREAD

**Issue by Jens0512** [Vurich/zig-kak#1]
I downloaded the plugin with [`plug.kak`](https://github.com/andreyorst/plug.kak), then I open my file: `src/bf.zig`, `:echo %opt{filetype}` said zig, but there's no highlighting of any sort ─ all's black and white. I manually sourced and controlled that `zig-kak` was downloaded as it should, so `plug.kak` is probably not at fault AFAIC. 

Is there something I've missed? If so, I think instructions clarifying how to get this working should be added to the README.

Or is this a problem with `zig-kak`?

**Comment by rayonix** [comment]
This line 
`hook -group zig-highlight global WinSetOption filetype=zig %{ add-highlighter window ref zig }`
needs a '/' added to the end of window
`hook -group zig-highlight global WinSetOption filetype=zig %{ add-highlighter window/ ref zig }`

**Comment by Jens0512** [comment]
Aha, thanks! That worked
